//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bestshooter.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public string Fee { get; set; }
        public string FollowId { get; set; }
        public System.DateTime Date { get; set; }
        public int PurchaseNumber { get; set; }
        public string CardNumber { get; set; }
        public string BankName { get; set; }
        public string AssignmentNumber { get; set; }
        public Nullable<byte> Read { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
