//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bestshooter.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pack
    {
        public int Id { get; set; }
        public string Picture { get; set; }
        public string DescPicture { get; set; }
        public string Name { get; set; }
        public string Sentence { get; set; }
        public string Cont { get; set; }
        public string Fee { get; set; }
        public string Tags { get; set; }
        public string Keywords { get; set; }
        public int GameId { get; set; }
        public int Counter { get; set; }
        public string MovLink1 { get; set; }
        public string MovLink2 { get; set; }
        public string MovLink3 { get; set; }
        public string MovLink4 { get; set; }
        public string MovLink5 { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
