//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bestshooter.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public string Tags { get; set; }
        public string Links { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Tell { get; set; }
        public string Telegram { get; set; }
        public string Instagram { get; set; }
        public string Youtube { get; set; }
        public string Aparat { get; set; }
    }
}
